// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphapi

import (
	"github.com/theopenlane/dbx/internal/ent/generated"
)

// Return response for createDatabase mutation
type DatabaseCreatePayload struct {
	// Created database
	Database *generated.Database `json:"database"`
}

// Return response for deleteDatabase mutation
type DatabaseDeletePayload struct {
	// Deleted database ID
	DeletedID string `json:"deletedID"`
}

// Return response for updateDatabase mutation
type DatabaseUpdatePayload struct {
	// Updated database
	Database *generated.Database `json:"database"`
}

// Return response for createGroup mutation
type GroupCreatePayload struct {
	// Created group
	Group *generated.Group `json:"group"`
}

// Return response for deleteGroup mutation
type GroupDeletePayload struct {
	// Deleted group ID
	DeletedID string `json:"deletedID"`
}

// Return response for updateGroup mutation
type GroupUpdatePayload struct {
	// Updated group
	Group *generated.Group `json:"group"`
}
