# server settings
server:
  debug: true
  dev: true

  # tls settings
  tls:
    enabled: false

# db settings
db:
  debug: true
  driverName: libsql
  primaryDbSource: "file:dbx.db"
  multiWrite: false

turso:
  baseUrl: https://api.turso.tech
  orgName: "openlane"
  token: ""

providers:
    localEnabled: true
    tursoEnabled: false